### ISSUE TITLE
Some clean up

### ISSUE THREAD

**Issue by b-t-k** [dajare/anthony-trollope_phineas-redux#1]
Looks good.

You need to run typogrify and semanticate again as they make a bunch of small changes. Other than that I can't find any issues. Excellent job

**Comment by dajare** [comment]
Thanks, Bruce! Some notes:

- `typogrify` makes bad changes to ch. 1 (the "18—" obscure em-dash x2 *should* have a space after it); I've accepted the rest.
- I've added a comment on Fitz-Howard in Google Groups.

Hopefully this looks done!

**Comment by b-t-k** [comment]
Did you make the commit? I can't see it?

**Comment by dajare** [comment]
> Did you make the commit? I can't see it?

Doh! 🤦 I forgot to `push` to master. Done now! Sorry about that.....
